### PR TITLE
Do not soft-fail Dendrite on sytest.

### PR DESCRIPTION
**Pull request by clokep**
To avoid situations like https://github.com/matrix-org/sytest/pull/1011#issuecomment-777867984

CC @neilalexander / @Kegsay

### CODE REVIEW

**Comment by clokep** [comment]
I'm not sure on the difference between the normal and "Full HTTP APIs" runs though this includes all of them.

**Comment by kegsay** [comment]
Personally I only think we need 1 test (e.g Postgres/Monolith) given we're mainly checking for Sytest not for Dendrite. LGTM though

**Review by richvdh — CHANGES_REQUESTED** [review]
I don't think we've ever had a clean run of these, so I don't think we can merge this yet.

See https://buildkite.com/matrix-dot-org/sytest/builds?branch=develop

**Comment by clokep** [comment]
I'm going to close this since the ball isn't really in my court. 😢

**Pull request closed without merging**
