### PR TITLE
Add i18n diff check for Element desktop

### PR DESCRIPTION
**Pull request by germain-gg**
Blocked by vector-im/element-desktop#188

### CODE REVIEW

**Review by dbkr — APPROVED** [review]

**Comment by dbkr** [comment]
Presumably this doesn't want to be merged until the element PR as are merged

**Comment by germain-gg** [comment]
> Presumably this doesn't want to be merged until the element PR as are merged

Very true, I have updated the PR comment to add a little "blocked by" mention!

**Review by jryans — APPROVED** [review]
Seems reasonable to me, thanks!

**Comment by germain-gg** [comment]
@dbkr I do not have sufficient permissions to merge this.
vector-im/element-desktop#188 has landed, could you merge this PR?

**Comment by kegsay** [comment]
@gsouquet done

**Pull request merged**
